### PR TITLE
added the graph coloring

### PR DESCRIPTION
**Pull request by unna97**
This is a work in progress branch with respect to issue #77

### CODE REVIEW

**Comment by unna97** [comment]
@MridulS @rossbar @dschult  This is my first time creating a .md file from .ipynb. There are interactive visualizations in the notebook, is that okay?

**Review by rossbar — COMMENTED** [review]
I started to take a look at this but then was struck by the size of the `greedy_colouring.md` file - it's 36 MB! This is absolutely huge for a text file - I think there is a ton of embedded html that should be removed, but I don't have a good sense for how to do so nor how this file was created.

Either way, this will be the first bridge to cross before it's even possible to review the file!

**Comment by unna97** [comment]
@rossbar  Thank you for the feedback. I created interactive maps using folium for demonstration of four colour map theorem. I think that would be the biggest file. Would you like me to remove it?

**Comment by rossbar** [comment]
I'm going to go ahead and close this one since it's been stale for a while. That's not to say a coloring example wouldn't be a valuable addition. @unna97 if you're still interested in pursuing this, please start by removing the embedded html from the notebook to get this into a reviewable form, then please feel free to reopen!

**Comment by unna97** [comment]
@rossbar sure, will make changes and update soon!

**Pull request closed without merging**
