### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by squenson1**
Make the spelling of "indegree" consistent:
"in-degree" --> "indegree"

### CODE REVIEW

**Comment by dschult** [comment]
Consistent with what? What are you matching with?

**Comment by squenson1** [comment]
"Consistent" meaning one spelling or the other, not both in such a short text, it is very confusing (even if both seems to be accepted in the literature).

**Comment by rossbar** [comment]
FWIW I think we should actually go the opposite direction, i.e. "indegree" -> "in-degree". The reason being consistency with NetworkX itself, which clearly favors the latter spelling. You can verify this with grep:

```bash
# In the networkx source repo
$ grep -rIo "indegree" | wc -l
30
$ grep -rIo "in-degree" | wc -l
58
```

All of the instances of `indegree` are variable names in code, so `in-degree` is the clear winner for documentation!

**Comment by squenson1** [comment]
Fine for me, one spelling or the other but not both!

**Review by rossbar — APPROVED** [review]
LGTM, thanks @squenson1 !

**Pull request merged**
