### PR TITLE
SNA on contact

### PR DESCRIPTION
**Pull request by Lukong123**

### CODE REVIEW

**Comment by Lukong123** [comment]
Hello sir @MridulS, please sir I can't figure out why these checks are failing.  Please can you enlighten me more?

**Comment by rossbar** [comment]
It looks like this PR actually includes the changes from #70 as well. It'd be best to split that out - if you're comfortable rebasing/cherry-picking you should be able to drop the commits related to the `distance_measures` notebook. If not, it's also fine just to `git rm` the distance measures directory (everything will be squashed at merge time anyways!) LMK if you have any questions!

**Comment by Lukong123** [comment]
> It looks like this PR actually includes the changes from #70 as well. It'd be best to split that out - if you're comfortable rebasing/cherry-picking you should be able to drop the commits related to the `distance_measures` notebook. If not, it's also fine just to `git rm` the distance measures directory (everything will be squashed at merge time anyways!) LMK if you have any questions!


Okay sir, thanks for pointing that out, I am not yet comfortable with `rebasing/cherry-picking` I'll  try using `git rm ` instead.  so I think I will leave just [https://github.com/networkx/nx-guides/pull/73/commits/a9d21719e3bac9307e5e24d967965b551a9e5970](url) and [https://github.com/networkx/nx-guides/pull/73/commits/3d04e24438eaedf9d7464b1c431e3192697935c8](url)

**Comment by rossbar** [comment]
I'm going to go ahead and close this as it's been stale for a while and still has the "changesets from multiple PRs" issue. @Lukong123 if you're still interested in working on this, the place to start would be to isolate the changes that were intended to be in this PR and push those up. Please feel free to reopen after doing so!

**Pull request closed without merging**
